// <auto-generated />
using System;
using System.Collections.Generic;
using DatabaseBroker;
using Entity.Models.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseBroker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240704062305_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.AboutBusinessModel.AboutBusinessModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("imageId");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("about_business");
                });

            modelBuilder.Entity("Entity.Models.Contact.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EmailId")
                        .HasColumnType("bigint")
                        .HasColumnName("email_id");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<MultiLanguageField>("Name")
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<long>("PhoneNumberId")
                        .HasColumnType("bigint")
                        .HasColumnName("phone_number_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PhoneNumberId");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("Entity.Models.Contact.EmailModel.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<MultiLanguageField>("Name")
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.HasKey("Id");

                    b.ToTable("email");
                });

            modelBuilder.Entity("Entity.Models.Contact.LocationModel.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("Home")
                        .HasColumnType("text")
                        .HasColumnName("home");

                    b.Property<MultiLanguageField>("Name")
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.ToTable("location");
                });

            modelBuilder.Entity("Entity.Models.Contact.PhoneNumberModel.PhoneNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Name")
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("WorkingDayStart")
                        .HasColumnType("text")
                        .HasColumnName("working_day_start");

                    b.Property<string>("WorkingDayStop")
                        .HasColumnType("text")
                        .HasColumnName("working_day_stop");

                    b.Property<string>("WorkingTimeStart")
                        .HasColumnType("text")
                        .HasColumnName("working_time_start");

                    b.Property<string>("WorkingTimeStop")
                        .HasColumnType("text")
                        .HasColumnName("working_time_stop");

                    b.HasKey("Id");

                    b.ToTable("phone_number");
                });

            modelBuilder.Entity("Entity.Models.FaqQuestion.FaqQuestions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("faq_questions");
                });

            modelBuilder.Entity("Entity.Models.File.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("file_model");
                });

            modelBuilder.Entity("Entity.Models.FutureModel.Future", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AboutBusinessModelId")
                        .HasColumnType("bigint");

                    b.Property<MultiLanguageField>("Text")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AboutBusinessModelId");

                    b.ToTable("futures");
                });

            modelBuilder.Entity("Entity.Models.HomeModel.HomeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<List<Guid>>("ImageIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("image_id");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("home_model");
                });

            modelBuilder.Entity("Entity.Models.MessageModel.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Entity.Models.Motto.Motto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<MultiLanguageField>("Text")
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("motto");
                });

            modelBuilder.Entity("Entity.Models.News.News", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Category")
                        .HasColumnType("jsonb")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<MultiLanguageField>("PostBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_body");

                    b.Property<MultiLanguageField>("PostTitle")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_title");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("posted_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("news");
                });

            modelBuilder.Entity("Entity.Models.OurServices.OurService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("AboutService")
                        .HasColumnType("jsonb")
                        .HasColumnName("about_service");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceIconId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_icon_id");

                    b.Property<MultiLanguageField>("ServiceName")
                        .HasColumnType("jsonb")
                        .HasColumnName("service_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("our_services");
                });

            modelBuilder.Entity("Entity.Models.PPS.PlaningModel.Planing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("planing");
                });

            modelBuilder.Entity("Entity.Models.PPS.PpsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PlaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("planing_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("SuccessId")
                        .HasColumnType("bigint")
                        .HasColumnName("success_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaningId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SuccessId");

                    b.ToTable("pps_model");
                });

            modelBuilder.Entity("Entity.Models.PPS.ProjectModel.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("project");
                });

            modelBuilder.Entity("Entity.Models.PPS.SuccessModel.Success", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiLanguageField>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<MultiLanguageField>("Title")
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("success");
                });

            modelBuilder.Entity("Entity.Models.ServicePercent.ServicePercent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<MultiLanguageField>("ServiceName")
                        .HasColumnType("jsonb")
                        .HasColumnName("service_name");

                    b.Property<float>("ServicePerecnt")
                        .HasColumnType("real")
                        .HasColumnName("service_percent_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("service_percent");
                });

            modelBuilder.Entity("Entity.Models.TeamMember.TeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasColumnType("jsonb")
                        .HasColumnName("full_name");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_id");

                    b.Property<MultiLanguageField>("Role")
                        .HasColumnType("jsonb")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("team_members");
                });

            modelBuilder.Entity("Entity.Models.Translation.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("En")
                        .HasColumnType("text")
                        .HasColumnName("en")
                        .HasAnnotation("Relational:JsonPropertyName", "en");

                    b.Property<string>("Ru")
                        .HasColumnType("text")
                        .HasColumnName("ru")
                        .HasAnnotation("Relational:JsonPropertyName", "ru");

                    b.Property<string>("Uz")
                        .HasColumnType("text")
                        .HasColumnName("uz")
                        .HasAnnotation("Relational:JsonPropertyName", "uz");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("translations");
                });

            modelBuilder.Entity("Entity.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("IsSigned");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entity.Models.Contact.Contact", b =>
                {
                    b.HasOne("Entity.Models.Contact.EmailModel.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Contact.LocationModel.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Contact.PhoneNumberModel.PhoneNumber", "PhoneNumber")
                        .WithMany()
                        .HasForeignKey("PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Location");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Entity.Models.FutureModel.Future", b =>
                {
                    b.HasOne("Entity.Models.AboutBusinessModel.AboutBusinessModel", null)
                        .WithMany("Futures")
                        .HasForeignKey("AboutBusinessModelId");
                });

            modelBuilder.Entity("Entity.Models.PPS.PpsModel", b =>
                {
                    b.HasOne("Entity.Models.PPS.PlaningModel.Planing", "Planing")
                        .WithMany()
                        .HasForeignKey("PlaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.PPS.ProjectModel.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.PPS.SuccessModel.Success", "Success")
                        .WithMany()
                        .HasForeignKey("SuccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planing");

                    b.Navigation("Project");

                    b.Navigation("Success");
                });

            modelBuilder.Entity("Entity.Models.AboutBusinessModel.AboutBusinessModel", b =>
                {
                    b.Navigation("Futures");
                });
#pragma warning restore 612, 618
        }
    }
}
