version: '3.8'

services:
  web:
    image: ${DOCKER_USERNAME}/forege_dialog
    build:
      context: .
      dockerfile: ForegeDialog/Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
