version: '3.8'

services:
  web:
     image:  ${{ secrets.DOCKER_USERNAME }}/british_analytica 
    build:
      context: .
      dockerfile: BritishAnalytica/Web/Dockerfile
    ports:
      - "2005:3050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
