version: '3.8'

services:
  web:
     image: $DOCKER_USERNAME/british_analytica 
    build:
      context: .
      dockerfile: BritishAnalytica/Web/Dockerfile
    ports:
      - "2005:3050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
