version: '3.8'

services:
  web:
    image: ${DOCKER_USERNAME}/british_analytica
    build:
      context: .
      dockerfile: BritishAnalytica/Web/Dockerfile
    ports:
      - "45.10.162.54:8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
