name: Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: golibjonabdurasulov
      DOCKER_PASSWORD: dckr_pat_h45zNBIQWRW1tTM7CDESY0Q7-dU
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker compose build

      - name: Push Docker image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker compose push

  Deploy:
    name: Deploy
    needs: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          key: ${{ secrets.HOST_KEY }}
          username: ${{ secrets.HOST_USERNAME }}
          script: |
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            docker-compose down
            docker-compose pull
            docker-compose --env-file .env up -d --no-deps --build
