name : Build and Deploy
on: 
  push:
    branches: 
    - main 

jobs:
 build: 
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
   uses: actions/chackout@v2
  - name: Setup .NET 8
   uses: actions/setup-dotnet@v1
   with:
     dotnet-version: '8.0.x'
  - name: Restore dependencies
   run: dotnet restore
  - name: dotnet build --configuration Release 
